version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sub_aggregator
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -h localhost -d sub_aggregator"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/sub_aggregator?sslmode=disable
      PORT: 8080
    depends_on:
      db:
        condition: service_healthy
    command: sh -c 'until pg_isready -U user -h db -d sub_aggregator; do sleep 1; done; ./main'

volumes:
  db-data: