basePath: /
definitions:
  pkg.CreateSubRequest:
    properties:
      end_date:
        example: 07-2026
        type: string
      price:
        example: 400
        type: integer
      service_name:
        example: Yandex Plus
        type: string
      start_date:
        example: 07-2025
        type: string
      user_id:
        example: 60601fee-2bf1-4721-ae6f-7636e79a0cba
        type: string
    type: object
  pkg.ErrorResponse:
    properties:
      error:
        example: Subscription not found
        type: string
    type: object
  pkg.GetSubsResponse:
    properties:
      subscriptions:
        items:
          $ref: '#/definitions/pkg.SubscriptionDTO'
        type: array
    type: object
  pkg.GetTotalCostResponse:
    properties:
      total_cost:
        example: 1200
        type: integer
    type: object
  pkg.SubscriptionDTO:
    properties:
      end_date:
        example: 07-2026
        type: string
      price:
        example: 400
        type: integer
      service_name:
        example: Yandex Plus
        type: string
      start_date:
        example: 07-2025
        type: string
      user_id:
        example: 60601fee-2bf1-4721-ae6f-7636e79a0cba
        type: string
    type: object
  pkg.UpdateSubRequest:
    properties:
      end_date:
        example: 08-2026
        type: string
      price:
        example: 500
        type: integer
      start_date:
        example: 08-2025
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: REST API for aggregating user subscriptions
  version: "1.0"
paths:
  /subscriptions:
    post:
      consumes:
      - application/json
      description: Creates a new subscription for a user
      parameters:
      - description: Subscription
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/pkg.CreateSubRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/pkg.SubscriptionDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg.ErrorResponse'
      summary: Create a new subscription
      tags:
      - subscriptions
  /subscriptions/{userID}:
    get:
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.GetSubsResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg.ErrorResponse'
      summary: Get all subscriptions for a user
      tags:
      - subscriptions
  /subscriptions/{userID}/{serviceName}:
    delete:
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: string
      - description: Service Name
        in: path
        name: serviceName
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/pkg.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg.ErrorResponse'
      summary: Delete a subscription
      tags:
      - subscriptions
    get:
      description: Get subscription by user ID and service name
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: string
      - description: Service Name
        in: path
        name: serviceName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.SubscriptionDTO'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/pkg.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg.ErrorResponse'
      summary: Get a subscription
      tags:
      - subscriptions
    put:
      consumes:
      - application/json
      description: Update by user ID and service name
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: string
      - description: Service Name
        in: path
        name: serviceName
        required: true
        type: string
      - description: Update payload
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/pkg.UpdateSubRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.SubscriptionDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/pkg.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg.ErrorResponse'
      summary: Update a subscription
      tags:
      - subscriptions
  /subscriptions/total-cost:
    get:
      description: Returns total subscription cost for a user in period; service filter
        optional
      parameters:
      - description: User ID
        in: query
        name: user_id
        required: true
        type: string
      - description: Start date MM-YYYY
        in: query
        name: start_date
        required: true
        type: string
      - description: End date MM-YYYY
        in: query
        name: end_date
        required: true
        type: string
      - description: Service name
        in: query
        name: service_name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.GetTotalCostResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg.ErrorResponse'
      summary: Get total cost by period
      tags:
      - subscriptions
swagger: "2.0"
